name: Locators
version: '1.1.0'
main: ru.nikita.locators.LocatorsPlugin
api-version: '1.16'
description: Настраиваемые предметы-локаторы для поиска игроков
commands:
  locators:
    description: Управление локаторами
    usage: /locators <give|reload>
    aliases: [locator]
permissions:
  locators.reload:
    description: Перезагрузка locators.json
    default: op
  locators.resetcooldown:
    description: Сброс cooldown локаторов режима 1
    default: op
